version: '3.8'
services:
  business:
    image: magnusandersen/gamelibrary:business
    restart: always
    environment:
      - DATABASE_HOST=app-database
    depends_on:
      - app-database
    ports:
      - 5001:8080

  app-database:
    image: mysql
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MY_S€cr€t_P@ssw0rD
      MYSQL_DATABASE: GameLib
    ports:
      - 63306:3306

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - app-database
