version: "3.9"

services:
  weather-api:
    image: magnusandersen/gamelibrary:prod
  
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  featurehub-h2-data:
